src/java/edu/psu/citeseerx/domain/ThinDoc.java
/*
 * Copyright 2007 Penn State University
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.psu.citeseerx.domain;

import java.io.Serializable;
import java.util.Date;
import edu.psu.citeseerx.utility.DateUtils;

/**
 * Light-weight bean container for document, citation, or cluster metadata.
 *
 * @author Isaac Councill
 * @version $Rev$ $Date$
 */
public class ThinDoc implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8919839426733776073L;
    
    private String doi;
    private Long cluster;
    private String authors;
    private String title;
    private String abs;
    private String venue;
    private String ventype;
    private int year = -1;
    private String pages;
    private int vol = -1;
    private int num = -1;
    private String publisher;
    private String tech;
    private int ncites = 0;
    private int selfCites = 0;
    private String snippet;
    private String url;
    private boolean inCollection; 
    private String observations;
    private Date updateTime;
    
    public String getAuthors() {
        return authors;
    } //- getAuthors
    public void setAuthors(String authors) {
        this.authors = authors;
    } //- setAuthors
    public Long getCluster() {
        return cluster;
    } //- getCluster
    public void setCluster(Long cluster) {
        this.cluster = cluster;
    } //- setCluster
    public String getDoi() {
        return doi;
    } //- getDoi
    public void setDoi(String doi) {
        this.doi = doi;
    } //- setDoi
    public int getNcites() {
        return ncites;
    } //- getNcites
    public void setNcites(int ncites) {
        this.ncites = ncites;
    } //- setNcites
    public int getSelfCites() {
        return selfCites;
    } //- getSelfCites
    public void setSelfCites(int selfCites) {
        this.selfCites = selfCites;
    } //- setSelfCites
    public String getTitle() {
        return title;
    } //- getTitle
    public void setTitle(String title) {
        this.title = title;
    } //- setTitle
    public String getVentype() {
        return ventype;
    } //- getVentype
    public void setVentype(String ventype) {
        this.ventype = ventype;
    } //- setVentype
    public String getVenue() {
        return venue;
    } //- getVenue
    public void setVenue(String venue) {
        this.venue = venue;
    } //- setVenue
    public int getYear() {
        return year;
    } //- getYear
    public void setYear(int year) {
        this.year = year;
    } //- setYear
    public String getAbstract() {
        return abs;
    } //- getAbstract
    public void setAbstract(String abs) {
        this.abs = abs;
    } //- setAbstract
    public String getSnippet() {
        return snippet;
    } //- getSnippet
    public void setSnippet(String snippet) {
        this.snippet = snippet;
    } //- setSnippet
    public String getUrl() {
        return url;
    } //- getUrl
    public void setUrl(String url) {
        this.url = url;
    } //- setUrl
    public boolean getInCollection() {
        return inCollection;
    } //- getInCollection
    public void setInCollection(boolean inCollection) {
        this.inCollection = inCollection;
    } //- setInCollection
    public String getAbs() {
        return abs;
    } //- getAbs
    public void setAbs(String abs) {
        this.abs = abs;
    } //- setAbs
    public int getNum() {
        return num;
    } //- getNum
    public void setNum(int num) {
        this.num = num;
    } //- setNum
    public String getPages() {
        return pages;
    } //- getPages
    public void setPages(String pages) {
        this.pages = pages;
    } //- setPages
    public String getPublisher() {
        return publisher;
    } //- getPublisher
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    } //- setPublisher
    public String getTech() {
        return tech;
    } //- getTech
    public void setTech(String tech) {
        this.tech = tech;
    } //- setTech
    public int getVol() {
        return vol;
    } //- getVol
    public void setVol(int vol) {
        this.vol = vol;
    } //- setVol
    public String getObservations() {
        return observations;
    } //- getObservations
    public void setObservations(String observations) {
        this.observations = observations;
    } //- setObservations
    public Date getUpdateTime() {
        return updateTime;
    } //- getUpdateTime
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    } //- setUpdateTime
    
    public String getRfc822Time() {
        return DateUtils.formatRFC822(updateTime);
    } //- getRfc822Time

    public String getRfc3339Time() {
        return DateUtils.formatRFC3339(updateTime);
    } //- getRfc3339Time

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    public String toString() {
        
        StringBuffer buf = new StringBuffer();
        
        buf.append("THINDOC\n");
        buf.append("DOI: "+doi+"\n");
        buf.append("CLUST: "+cluster+"\n");
        buf.append("AUTH: "+authors+"\n");
        buf.append("TITL: "+title+"\n");
        buf.append("ABS: "+abs+"\n");
        buf.append("VEN: "+venue+"\n");
        buf.append("VT: "+ventype+"\n");
        buf.append("YEAR: "+year+"\n");
        buf.append("PAGE: "+pages+"\n");
        buf.append("VOL: "+vol+"\n");
        buf.append("NUM: "+num+"\n");
        buf.append("PUBL: "+publisher+"\n");
        buf.append("TECH: "+tech+"\n");
        buf.append("NCITE: "+ncites+"\n");
        buf.append("SELFCITE: "+selfCites+"\n");
        buf.append("SNIP: "+snippet+"\n");
        buf.append("URL: "+url+"\n");
        buf.append("INCOL: "+inCollection+"\n"); 

        return buf.toString();
    } //- toString
    
    
}  //- class ThinDoc

src/java/edu/psu/citeseerx/myciteseer/domain/Feed.java
package edu.psu.citeseerx.myciteseer.domain;

import java.io.Serializable;

public class Feed implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8951832947365013271L;
    
    public static final String DOC_TYPE = "ds";
    public static final String CIT_TYPE = "cs";
    
    public static boolean isValidType(String type) {
        if (type.equals(DOC_TYPE) || type.equals(CIT_TYPE)) {
            return true;
        } else {
            return false;
        }
    }
    
    private long id;
    private String userid;
    private String title;
    private String desc;
    private String type;
    private String params;
    
    public String getDesc() {
        return desc;
    }
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getParams() {
        return params;
    }
    public void setParams(String params) {
        this.params = params;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getType() {
        return type;
    }
    public void setType(String type) {
        this.type = type;
    }
    public String getUserid() {
        return userid;
    }
    public void setUserid(String userid) {
        this.userid = userid;
    }
    
}

web/citeseerx_webapp/WEB-INF/jsp/csx/feeds/atom.jsp
<?xml version="1.0" encoding="UTF-8"?>
<%@ page language="java" pageEncoding="UTF-8" contentType="text/xml; charset=UTF-8" session="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<feed xmlns="http://www.w3.org/2005/Atom">
 <id><c:out value="${ feedLink }" escapeXml="true"/></id>
 <title type="html"><fmt:message key="app.name"/> <c:out value="${ feedTitle }"/></title>
 <updated><c:out value="${ feedDate }"/></updated>
 <author>
  <name><fmt:message key="app.name"/></name>
  <uri><c:out value="${ baseUrl }"/></uri>
 </author>
 <link rel="self" href="<c:out value="${ feedLink }" escapeXml="true"/>"/>
 <generator><fmt:message key="app.name"/> Atom Generator</generator>
 <c:forEach var="hit" items="${ hits }">
 <entry>
  <title type="html"><c:out value="${ hit.title }"/></title>
  <updated><c:out value="${ hit.rfc3339Time }"/></updated>
  
  <author>
   <name><c:out value="${ hit.authors }"/></name>
  </author>
  
  <c:if test="${ hit.inCollection }">
  <link rel="alternate" href="<c:url value="${ baseUrl }/viewdoc/summary"><c:param name="doi" value="${ hit.doi }"/></c:url>"/>
  <summary type="html"><c:out value="${ hit.abs }"/></summary>
  <id><c:out value="${ baseUrl }"/>/document/<c:out value="${ hit.doi }"/></id>
  </c:if>
  <c:if test="${ ! hit.inCollection }">
  <link rel="alternate" href="<c:url value="${ baseUrl }/showciting"><c:param name="cid" value="${ hit.cluster }"/></c:url>"/>
  <id><c:out value="${ baseUrl }"/>/cluster/<c:out value="${ hit.cluster }"/></id>
  </c:if>
 </entry>
 </c:forEach>
</feed>

web/citeseerx_webapp/WEB-INF/jsp/csx/feeds/rss.jsp
<?xml version="1.0" encoding="UTF-8"?>
<%@ page language="java" pageEncoding="UTF-8" contentType="text/xml; charset=UTF-8" session="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<rss version="2.0">
 <channel>
  <title><fmt:message key="app.name"/> <c:out value="${ feedTitle }"/></title>
  <link><c:out value="${ feedLink }" escapeXml="true"/></link>
  <description><fmt:message key="app.name"/> <c:out value="${ feedDesc }"/></description>
  <language>en-us</language>
  <pubDate><c:out value="${ feedDate }"/></pubDate>
  <generator>CiteSeerX RSS Generator</generator>
  <ttl>60</ttl>
  <c:forEach var="hit" items="${ hits }">
  <item>
   <title><c:out value="${ hit.title }"/></title>
   <pubDate><c:out value="${ hit.rfc822Time }"/></pubDate>
   <c:if test="${ hit.inCollection }">
   <link><c:url value="${ baseUrl }/viewdoc/summary"><c:param name="doi" value="${ hit.doi }"/></c:url></link>
   <description><c:out value="${ hit.abs }"/></description>
   <guid><c:out value="${ baseUrl }"/>/document/<c:out value="${ hit.doi }"/></guid>
   </c:if>
   <c:if test="${ ! hit.inCollection }">
   <link><c:url value="${ baseUrl }/showciting"><c:param name="cid" value="${ hit.cluster }"/></c:url></link>
   <guid><c:out value="${ baseUrl }"/>/cluster/<c:out value="${ hit.cluster }"/></guid>
   </c:if>
  </item>
  </c:forEach>
 </channel>
</rss>