src/java/edu/psu/citeseerx/domain/Table.java
package edu.psu.citeseerx.domain;
/*
 * Copyright 2007 Penn State University
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


import java.io.Serializable;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;

import org.jdom.Element;
import org.jdom.JDOMException;
import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;

/**
 * Light-weight bean container for table metadata.
 * 
 * @author Shuyi Zheng, Pradeep Teregowda
 */
public class Table implements Serializable, XMLSerializable
{
	/* Attributes of a table */
	private long id;
	private String tableID;
	private String proxyID;
	private String doi;
	private int inPage;
	private String content;
	private String reference;
	private String footNote;
	private String caption;
	/* The following are added so that it is easier to index
	 * the table.
	*/
	private int nCites;
	private int paperYear;
	private String authors;
	private String title;
	private String docURL;
	
	public static final long serialVersionUID = 2L;

	/* Fields for XML access */
	public static final String TABLE_ROOT = "table";
	public static final String TABLE_ID = "id";
	public static final String DOI_KEY = "doi";
	public static final String INPAGE = "pageNumInDoc";
	public static final String TABLE_CONTENT = "content";
	public static final String REFERENCES = "referenceText";
	public static final String FOOTNOTE = "footnote";
	public static final String CAPTION = "caption";

	protected static String[] fieldArray = {
		TABLE_ROOT, TABLE_ID, DOI_KEY, INPAGE, TABLE_CONTENT,
		REFERENCES, FOOTNOTE, CAPTION
	};
	
	public Table() {
		id = 0;
		tableID = "";
		doi = "";
		inPage = 0;
		content = "";
		reference ="";
		footNote = "";
		caption = "";
	/*
	 * Following are added so that tables play well with others
	 */
		nCites = 0;
		paperYear = 0;
		authors = "";
		title = "";
		docURL = "";
	}
   
	/*
	 * Getters and Setters for the Attributes
	 * 
	 */
	
	public long getID() {
		return id;
	}
	public void setID(long in) {
		id = in;
	}
	
    public String getTableID() {
    	return tableID;
    }
    public void setTableID(String id) {
    	tableID = id;
    }

    public String getProxyKey() {
    	return proxyID;
    }
    public void setProxyKey(String pid) {
    	proxyID = pid;
    }
    
    public String getPaperIDForTable() {
    	return doi;
    }
    public void setPaperIDForTable(String paperDOI) {
    	doi = paperDOI;
    }

    public int getTableOccursInPage() {
    	return inPage;
    }
    public void setTableOccursInPage(int page) {
    	inPage = page;
    }

    public String getContent() {
    	return content;
    }
    public void setContent(String tableContents) {
    	content = tableContents;
    }
    public String getLimitedContent() {
    	int maxint = content.length();
    	if(maxint > 65535) { maxint = 65535; }
    	return content.substring(0, maxint);	
    }

    public String getTableReference() {
    	return reference;
    }
    public void setTableReference(String references) {
    	reference = references;
    }

    public String getFootNote() {
    	return footNote;
    }
    public void setFootNote(String note) {
    	footNote = note;
    }

    public void setCaption(String captionInfo) {
    	caption = captionInfo;
    }
    public String getCaption() {
    	return caption;
    }
    
    
    public void setYear(int pYear) {
    	paperYear = pYear;
    }
    public int getYear() {
    	return paperYear;
    }
    
    public void setCitedBy(int count) {
    	nCites = count;
    }
    public int getCitedBy() {
    	return nCites;
    }
    
    public String getPaperAuthors() {
    	return authors;
    }
    public void setPaperAuthors(String commaSep) {
    	authors = commaSep;
    }
    
    public void setPaperTitle(String ttl) {
    	title = ttl;
    }
    public String getPaperTitle() {
    	return title;
    }
    public void setDocURL(String url) {
    	docURL = url;
    }
    public String getDocURL(String url) {
    	return docURL;
    }
    /*
     * (non-Javadoc)
     * Make the object attributes into a string
     * @see java.lang.Object#toString()
     */
    public String toString() {
    	
    	StringBuffer buf = new StringBuffer();
    	buf.append("ID: "+tableID+"\n");
    	buf.append("DOI: "+doi+"\n");
		buf.append("Page: "+Integer.toString(inPage)+"\n");
		buf.append("Content: "+content+"\n");
		buf.append("References: "+reference+"\n");
		buf.append("Footnotes: "+footNote+"\n");
		buf.append("Caption: "+caption+"\n");

		return buf.toString();
    }

    /*
     * (non-Javadoc)
     * Use build XML to return the string
     * @see edu.psu.citeseerx.domain.XMLSerializable#toXML(boolean)
     */
    public String toXML(boolean s) {
	StringBuffer xml = new StringBuffer();
        buildXML(xml, s);
        return xml.toString();
    }

    /*
     * (non-Javadoc)
     * 
     * @see edu.psu.citeseerx.domain.XMLSerializable#toXML(java.io.OutputStream, boolean)
     */
    
    public void toXML(OutputStream out, boolean sysData) throws IOException {
        StringBuffer xml = new StringBuffer();
        buildXML(xml, sysData);
        out.write(xml.toString().getBytes("utf-8"));
    }

    public void fromXML(InputStream xmlin) throws IOException {
    	SAXBuilder builder = new SAXBuilder();
        try {
            org.jdom.Document doc = builder.build(xmlin);
            Element root = doc.getRootElement();
            fromXML(root);
            
        } catch (JDOMException e) {
            e.printStackTrace();
        }
        
    }


    public void fromXML(Element root) throws JDOMException {
	if(!root.getName().equals(TABLE_ROOT)) {
		throw new JDOMException("Root is "+root.getName()+" expected "
		        +TABLE_ROOT);
	}
	else {
		tableID = root.getAttributeValue(TABLE_ID);
		List<Element> rootChildren = root.getChildren();
        	for (Iterator<Element> it = rootChildren.iterator(); 
        	it.hasNext(); ) {
            Element child = (Element)it.next();
	     	if (child.getName().equals(INPAGE)) {
				inPage = Integer.parseInt(child.getValue());
			}
			else if (child.getName().equals(CAPTION)) {
				caption = child.getValue();
			}
			else if (child.getName().equals(TABLE_CONTENT)) {
				XMLOutputter cout = new XMLOutputter();
				content = cout.outputString(child);
			}
			else if (child.getName().equals(FOOTNOTE)) {
				footNote = child.getValue();
			}
			else if (child.getName().equals(REFERENCES)) {
				reference = child.getValue(); 
			}
        }
	}
	
    }

    public void buildXML(StringBuffer xml, boolean sysData) {
    	Element tabRec = buildXML(); 
		XMLOutputter bXML = new XMLOutputter();
		String tout = bXML.outputString(tabRec);
		xml.append(tout);
    }
    
    public Element buildXML() {
    	Element tabRec = new Element(TABLE_ROOT);
    	tabRec.setAttribute(TABLE_ID,tableID);
    	Element inpageXML = new Element(INPAGE);
    	tabRec.addContent(inpageXML);
    	inpageXML.addContent(Integer.toString(inPage));
    	Element capXML = new Element(CAPTION);
    	capXML.addContent(caption);
    	tabRec.addContent(capXML);
    	Element cXML = new Element(TABLE_CONTENT);
    	cXML.addContent(content);
    	tabRec.addContent(cXML);
    	Element footE = new Element(FOOTNOTE);
    	footE.addContent(footNote);
		tabRec.addContent(footE);
		Element referXML = new Element(REFERENCES);
		tabRec.addContent(referXML);
		return tabRec;
    }
    
}

src/java/edu/psu/citeseerx/myciteseer/web/search/PeopleAdvancedSearchFormController.java
/*
 * Copyright 2007 Penn State University
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.psu.citeseerx.myciteseer.web.search;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.validation.BindException;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;

import edu.psu.citeseerx.myciteseer.domain.PeopleAdvancedSearch;
import edu.psu.citeseerx.webutils.RedirectUtils;

/**
 * Form controller to handle advance search options for People Search.
 * @see org.springframework.web.servlet.mvc.SimpleFormController
 * @author Juan Pablo Fernandez Ramirez
 * @version $Rev$ $Date$
 */
public class PeopleAdvancedSearchFormController extends SimpleFormController {
	private String peopleSearchURL = "/myciteseer/search/peoplesearch";

	/**
	 * @param peopleSearchURL URL to PeopleSearch
	 */
	public void setPeopleSearchURL(String peopleSearchURL) {
		this.peopleSearchURL = peopleSearchURL;
	} //- setPeopleSearchURL
	
	public PeopleAdvancedSearchFormController() {
		setSessionForm(true);
        setValidateOnBinding(false);
        setCommandName("peopleAdvancedSearch");
        setFormView("MCSAdvancedSearch");
	} //- PeopleAdvancedSearchFormController

	/* (non-Javadoc)
	 * @see org.springframework.web.servlet.mvc.AbstractFormController#formBackingObject(javax.servlet.http.HttpServletRequest)
	 */
	@Override
	protected Object formBackingObject(HttpServletRequest request)
			throws Exception {
		return new PeopleAdvancedSearch();
	} //- formBackingObject

	/* (non-Javadoc)
	 * @see org.springframework.web.servlet.mvc.BaseCommandController#onBindAndValidate(javax.servlet.http.HttpServletRequest, java.lang.Object, org.springframework.validation.BindException)
	 */
	@Override
	protected void onBindAndValidate(HttpServletRequest request,
			Object command, BindException errors) throws Exception {
		//PeopleAdvancedSearch peopleAdvancedSearch = (PeopleAdvancedSearch)command;
		//getValidator().validate(peopleAdvSearch, errors);
	} //- onBindAndValidate

	/* (non-Javadoc)
	 * @see org.springframework.web.servlet.mvc.SimpleFormController#onSubmit(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse, java.lang.Object, org.springframework.validation.BindException)
	 */
	@Override
	protected ModelAndView onSubmit(HttpServletRequest request,
			HttpServletResponse response, Object command, BindException errors)
			throws Exception {
		onBindAndValidate(request, command, errors);
        if (errors.hasErrors()) {
            return showForm(request, response, errors);
        }
        PeopleAdvancedSearch peopleAdvancedSearch = 
        	(PeopleAdvancedSearch)command;
        String path = peopleSearchURL + peopleAdvancedSearch.getQuery();
        System.out.println("Select path: " + path);
        RedirectUtils.sendRedirect(request, response, path);
        return null;
	} //- onSubmit
	
	
} //- class PeopleAdvancedSearchFormController

src/java/edu/psu/citeseerx/web/HealthCheckController.java
/*
 * Copyright 2007 Penn State University
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.psu.citeseerx.web;

import org.springframework.web.servlet.mvc.Controller;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.ServletException;
import javax.servlet.http.*;

import java.io.*;

public class HealthCheckController implements Controller {

    public ModelAndView handleRequest(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {
        return new ModelAndView("healthCheck", null);
    }
}

src/java/edu/psu/citeseerx/web/NewDocController.java
/*
 * Copyright 2007 Penn State University
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.psu.citeseerx.web;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import edu.psu.citeseerx.dao2.logic.CSXDAO;
import edu.psu.citeseerx.domain.Document;
import edu.psu.citeseerx.domain.DomainTransformer;
import edu.psu.citeseerx.domain.ThinDoc;

/**
 * List the last document additions to the corpus
 * @author Juan Pablo Fernandez Ramirez
 * @version $Rev$ $Date$
 */
public class NewDocController implements Controller {

    private CSXDAO csxdao;
    
    public void setCSXDAO(CSXDAO csxdao) {
        this.csxdao = csxdao;
    } //- setCSXDAO
    
    private int nrows = 10;
    
    public void setNrows(int nrows) {
        this.nrows = nrows;
    } //- setNrows
    
    /* (non-Javadoc)
     * @see org.springframework.web.servlet.mvc.Controller#handleRequest(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
     */
    public ModelAndView handleRequest(HttpServletRequest request,
            HttpServletResponse response) throws Exception {

        String lastDOI = request.getParameter("last");
        lastDOI = (lastDOI == null || lastDOI.trim().length() == 0) ? "Z" :
            lastDOI;
        
        List<String> dois = csxdao.getLastDocuments(lastDOI, nrows);

        List<ThinDoc> hits = new ArrayList<ThinDoc>(); 
        for (String doi : dois) {
            Document doc = csxdao.getDocumentFromDB(doi, false, true);
            if (doc.isPublic()) {
                ThinDoc tDoc = DomainTransformer.toThinDoc(doc);
                // We do know that all documents here are in the corpus
                tDoc.setInCollection(true);
                tDoc.setAbstract(doc.getDatum(Document.ABSTRACT_KEY));
                if ( tDoc.getAbstract() != null &&
                        tDoc.getAbstract().length() > 0) {
                    int limit = Math.min(tDoc.getAbstract().length(), 200);
                    tDoc.setSnippet(
                            doc.getDatum(Document.ABSTRACT_KEY).substring(0, limit));

                }
                hits.add(tDoc);
            }
        }

        HashMap<String, Object> model = new HashMap<String, Object>();
        model.put("hits", hits);
        
        StringBuffer nextPageParams = null;
        if (hits.size() > 0) {
            nextPageParams = new StringBuffer();
            nextPageParams.append("last=");
            nextPageParams.append(hits.get(hits.size()-1).getDoi());
            model.put("nextPageParams", nextPageParams);
            model.put("nfound", hits.size());
        }

        String banner = csxdao.getBanner();
        if (banner != null && banner.length() > 0) {
            model.put("banner", banner);
        }
        
        // Generate title, description and keywords meta tag values.
        String pageTitle, pageDescription, pageKeywords;
        
        pageTitle = pageDescription = pageKeywords = 
            "Latest ingested documents";
        
        model.put("pagetitle", pageTitle);
        model.put("pagedescription", pageDescription);
        model.put("pagekeywords", pageKeywords);
        model.put("nrows", nrows);

        return new ModelAndView("newDocs", model);
    } //- handleRequest

} //- class NewDocController

web/citeseerx_webapp/WEB-INF/jsp/csx/activeBib.jsp
<%@ include file="shared/IncludeDocHeader.jsp" %>
<div id="viewContent">
  <h3>Active Bibliography</h3>
  <c:if test="${empty citations}">
    <p class="para4">No active bibliography identified.</p>
  </c:if>
  <c:if test="${!empty citations}">
    <table class="refs">
      <c:forEach var="citation" items="${ citations }">
        <tr><td class="title">
          <c:if test="${ citation.ncites > 0 }"><c:out value="${ citation.ncites }"/></c:if>
        </td><td>
          <c:if test="${ citation.inCollection }"><a href="<c:url value="/viewdoc/summary?cid=${ citation.cluster }"/>"><c:out value="${ citation.title }"/></a></c:if>
          <c:if test="${ ! citation.inCollection }"><a href="<c:url value="/showciting?cid=${ citation.cluster }"/>"><c:out value="${ citation.title }"/></a></c:if>
          &ndash; <c:out value="${ citation.authors }"/>
          <c:if test="${ citation.year > 0 }"> - <c:out value="${ citation.year }"/></c:if>
        </td></tr>
      </c:forEach>
    </table>
  </c:if>
</div>
<div class="clear"></div>
</div>
<%@ include file="../shared/IncludeFooter.jsp" %>

web/citeseerx_webapp/WEB-INF/jsp/csx/authMerge.jsp
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ include file="../shared/IncludeHeader.jsp" %>
<div id="main">
<%@ include file="../shared/IncludeSearchBox.jsp" %>

<div id="viewContent">

	<div id="right-sidebar"> <!-- Contains left content -->
	<div class="inside"> <!-- to give some room between columns -->
	</div> <!--End inside -->
	</div> <!-- End of right-sidebar --> 
	<br/>

    <c:if test="${ ! correctionsEnabled }">
		<h3><font color="red">Corrections are currently disabled!</font></h3>
	</c:if>
	<c:if test="${ correctionsEnabled }">

		<c:if test="${ error }">
			<h3><font color="red"><c:out value="${ errMsg }"/></font></h3>
		</c:if>

		<h3>Correct metadata errors for this author (login required)</h3>
		<!--p class="char_increased">......</p-->

		<h4><font color="red"><c:out value="${ message }"/></font></h4>

		<br/>		
		<p><font color="red">Fields marked with<span class="reqMark">*</span> are required to be non-empty.</font></p>

        <div id="textfields" class="fieldSet">
		<form id="correctionForm" method="post" action="" class="wform labelsRightAligned">
		<fieldset>
		<h3>Primary Author</h3>
		<table>
		<spring:bind path="command.uauth.canname">
	        <tr><td><label for="<c:out value="${ status.expression }"/>" class="preField">Canonical Name*:</label></td>
			<td><input type="text" size="100" id="<c:out value="${ status.expression }"/>" name="<c:out value="${ status.expression }"/>" value="<c:out value="${ status.value }"/>" class=""/></td></tr>
		</spring:bind>

		<spring:bind path="command.uauth.affil">
	        <tr><td><label for="<c:out value="${ status.expression }"/>" class="preField">Affiliation*:</label></td>
			<td><input type="text" size="100" id="<c:out value="${ status.expression }"/>" name="<c:out value="${ status.expression }"/>" value="<c:out value="${ status.value }"/>" class=""/></td></tr>
		</spring:bind>

		<spring:bind path="command.uauth.ndocs">
	        <tr><td><label for="<c:out value="${ status.expression }"/>" class="preField">#Publications:</label></td>
			<td><c:out value="${ status.value }"/></td></tr>
		</spring:bind>

		<spring:bind path="command.uauth.hindex">
	        <tr><td><label for="<c:out value="${ status.expression }"/>" class="preField">H-index:</label></td>
			<td><c:out value="${ status.value }"/></td></tr>
		</spring:bind>
		</table>
		</fieldset>

		<input type="submit" class="primaryAction" id="submit" name="correctInfo" value="Correct Metadata" />
		<br><br>

		<c:set var="limit" value="15" />
        <c:if test="${ param.list == 'full' }">
        <c:set var="limit" value="${ command.ndocs }" />
        </c:if>

		<h3>Top publications</h3><br>
		<table class="refs">
		<tr><td></td><td>#Cites</td><td>Title</td></tr>
		<c:forEach var="doc" items="${ command.docs }" begin="0" end="${limit - 1}">
			<tr>
			<td><input type="checkbox" name="<c:out value="${ doc.cluster }"/>" 
				       value="<c:out value="${ doc.cluster }"/>" /></td>
			<td><font color="purple"><c:out value="${ doc.ncites }"/></font></td>
			<td><a href="<c:url value="/viewdoc/summary?doi=${ doc.doi }"/>"><c:out value="${ doc.title }"/></a> - <c:out value="${ doc.year }"/></td>
			</tr>
		</c:forEach>
		</table>

        <c:if test="${ command.ndocs > 15 }">
        <c:choose>
 		  <c:when test="${param.list=='full'}">
			<c:url value="authmerge" var="editUrl">
			  <c:param name="aid" value="${ param.aid }"/>
			  <c:if test="${!empty param.query}"><c:param name="query" value="${ param.query }"/></c:if>
			  <c:if test="${!empty param.cstart}"><c:param name="cstart" value="${ param.cstart }"/></c:if>
			</c:url>
		  	<p><a class="link" href="<c:out value="${editUrl}"/>">View shorten publications << </a></p>
		  </c:when>
		<c:otherwise>
			<c:url value="authmerge" var="editUrl">
			  <c:param name="aid" value="${ param.aid }"/>
			  <c:if test="${!empty param.query}"><c:param name="query" value="${ param.query }"/></c:if>
			  <c:if test="${!empty param.cstart}"><c:param name="cstart" value="${ param.cstart }"/></c:if>
			  <c:param name="list" value="full"/>
			</c:url>
		   <p><a class="link" href="<c:out value="${editUrl}"/>">View completed publications >> </a></p>
		</c:otherwise>
		</c:choose>
		</c:if> 

		<br>
		<input type="submit" class="primaryAction" id="submit" name="removePapers" value="Remove Selected Publications" />
		</form>
		</div>

		<div id="textfields" class="fieldSet">
		<fieldset>
		<h3>Possible Confused Authors</h3>
		<span class="char_decreased"><font color="red">Secondary authors to merge with the primary author</font></span>
		<br>
		<table>
		<span class="oneField">
			<form id="loadingForm" method="get" action="" class="wform labelsRightAligned">
		    <tr><td><label class="preField">Author to Merge:</label></td>
			<input type="hidden" size="20" id="aid" name="aid" value="${ command.uauth.aid }" class=""/>
			<td><input type="text" size="20" id="query" name="query" value="${ command.query }" class=""/>
			<input type="submit" class="primaryAction" id="load" value="Load"/>
			<font color="red">Search for desired authors to merge</font></td></tr>
			</form>
		</span>
		</table>
		</fieldset>

		<form id="mergingForm" method="post" action="" class="wform labelsRightAligned">
		<table class="refs">
        <c:forEach var="auth" items="${ command.candidates }">
			<tr>
			<td>
                <!-- input type="radio" name="gender" value="F" /></td -->
				<input type="radio" name="merge_author" value="<c:out value="${ auth.aid }"/>"  /></td>
			<td width="120"><font color="purple"><a href="viewauth/summary?aid=<c:out value="${ auth.aid }" />"><c:out value="${ auth.canname }"/></a></font></td>
			<td width="600"><font><c:out value="${ auth.affil }"/></font></td>
			<td><font><c:out value="${ auth.ndocs }"/> pubs</font></td>
			</tr>
		</c:forEach>
		<tr><td></td>
			<td></td>
			<td></td></tr>
		</table>
		<br>
		<c:if test="${ command.nextCandidatePage != null }">
        <div style="margin:0 0 0 30pt;">
 			<a href="authmerge?<c:out value="${ command.nextCandidatePage }" /> "> Next Page >> </a>
        </div>
		</c:if>

		<br>
		<input type="submit" class="primaryAction" id="submit" name="mergeAuthors" value="Merge selected authors" />
		</form>
		</div>
	</c:if>
</div>
<%@ include file="../shared/IncludeFooter.jsp" %>

web/citeseerx_webapp/WEB-INF/jsp/csx/healthCheck.jsp
<html>
<head>
<title>CSX Health Check</title>
</head>
<body>
HEALTH CHECK PASSED
</body>
</html>

web/citeseerx_webapp/WEB-INF/jsp/csx/searchTables.jsp
<%@ include file="../shared/IncludeHeader.jsp" %>
<%-- Put your searchbox here. Best pratice is to customize and keep classes and ids. --%>
<div id="main">
<%@ include file="../shared/IncludeSearchBox.jsp" %>

  <div id="content" class="sidebar">
    
    <%@ include file="shared/IncludeResultsSidebar.jsp" %>
    <div id="result_info">
      <%@ include file="shared/IncludeResultsInfo.jsp" %>
      <%@ include file="shared/IncludeResultsPager.jsp" %>
    </div>
    <div id="result_list">
      <%-- Check to make sure we actually got results --%>
      <c:choose>
        <c:when test="${ nfound == 0 }">
          <%-- Display error for no results --%>
          <div class="error"><%@ include file="shared/IncludeResultsError.jsp" %></div>
        </c:when>
        <c:otherwise>
          <%-- Sorting Dropdown--%>
          <c:if test="${ error }"><div class="error"><c:out value="${ errorMsg }" escapeXml="false"/></div></c:if>
          <c:forEach var="hit" items="${ hits }" varStatus="status">
            <div class="result">
            <h3><c:out value="${ hit.caption }" escapeXml="false"/></h3>
                       
  <div class="doc">
    in <a href="viewdoc/summary?doi=${ hit.paperIDForTable }" ><c:out value="${ hit.paperTitle }" escapeXml="false"/></a>
  </div>
<div class="pubinfo">

  <span class="authors">by
    <c:if test="${ ! empty hit.paperAuthors }"><c:out value="${ hit.paperAuthors }"/></c:if>
    <c:if test="${ empty hit.paperAuthors }">unknown authors</c:if>
  </span>
  <span class="pubyear">
    <c:if test="${ ! empty hit.year && hit.year > 0 }"><c:out value="${ hit.year }"/></c:if>
  </span>
</div>
  <div class="snippet">
    <c:if test="${! empty hit.tableReference}">"... <c:out value="${ hit.tableReference }" escapeXml="false"/> ..."</c:if>
  </div>
<div class="pubextras">
  <c:if test="${ !empty hit.citedBy && hit.citedBy > 0 }">
    Cited by <c:out value="${ hit.citedBy }"/>
  </c:if>
</div>

   
            <div class="snippet">
              <c:if test='${ param.tc eq "true" }'>
                <c:out value="${ hit.content }" escapeXml="false"/>
              </c:if>
            </div>
          </div>


        </c:forEach>
        </c:otherwise>
      </c:choose>
    </div>
    <c:if test="${ nfound != 0}">
      <div id="result_info">
        <%@ include file="shared/IncludeResultsPager.jsp" %>
        <%@ include file="shared/IncludeResultsInfo.jsp" %>
      </div>
    </c:if>
  </div>
<div class="clear"></div>
</div>
<%@ include file="../shared/IncludeFooter.jsp" %>